heat_template_version: 2018-08-31

description: >
  Deploy base infrastructure for the NCR core platform.
  A lot of this structure is stolen (with permission) from Erik Hjelmås,
  and his IaC course at NTNU.
  Thanks Erik <3

parameters:
  admin_networks_v4:
    type: comma_delimited_list
    label: admin_networks
    description: A list of IPv4 networks that will be allowed SSH access
  admin_networks_v6:
    type: comma_delimited_list
    label: admin_networks
    description: A list of IPv6 networks that will be allowed SSH access
  core_net_name:
    type: string
    description: Name for core network
    default: NCR-Core-Net
  domain:
    type: string
    description: Domain name for the deployed environment
  key_name:
    type: string
    description: SSH key for all servers
  ipv6_subnetpool:
    type: string
    description: ID for default IPv6 subnet pool
  os_image:
    type: string
    description: Default OS for all servers
    default: Ubuntu Server 20.04 LTS (Focal Fossa) amd64
  public_net:
    type: string
    description: ID or name of external net for router
  puppet_flavor:
    type: string
    description: Flavor for puppetmaster/puppetdb
    default: m1.medium
  postgres_flavor:
    type: string
    description: Flavor for postgres
    default: m1.small
  rabbitmq_flavor:
    type: string
    description: Flavor for rabbitmq
    default: m1.small
  docker_flavor:
    type: string
    description: Flavor for dockerhost
    default: m1.large

resources:
# Network stuff
  core_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: core_net_name }

  core_subnet_v4:
    type: OS::Neutron::Subnet
    properties:
      name: NCR-Core-v4
      network: { get_resource: core_net }
      cidr: 192.168.0.0/24
      gateway_ip: 192.168.0.1
      allocation_pools:
        - start: 192.168.0.100
          end: 192.168.0.254

  core_subnet_v6:
    type: OS::Neutron::Subnet
    properties:
      name: NCR-Core-v6
      network: { get_resource: core_net }
      ip_version: 6
      ipv6_address_mode: slaac
      ipv6_ra_mode: slaac
      subnetpool: { get_param: ipv6_subnetpool }

  core_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  core_router_interface_v4:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: core_router }
      subnet_id: { get_resource: core_subnet_v4 }

  core_router_interface_v6:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: core_router }
      subnet_id: { get_resource: core_subnet_v6 }

# Security Groups
  sg_linux_v4:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Common rules for Linux servers
      rules:
        repeat:
          for_each:
            <%net%>: { get_param: admin_networks_v4 }
          template:
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            remote_ip_prefix: <%net%>

  sg_linux_v6:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Common rules for Linux servers
      rules:
        repeat:
          for_each:
            <%net%>: { get_param: admin_networks_v6 }
          template:
            protocol: tcp
            ethertype: IPv6
            port_range_min: 22
            port_range_max: 22
            remote_ip_prefix: <%net%>

  sg_linux_in4_icmp:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: sg_linux_v4 }
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0

  sg_linux_in6_icmp:
    type: OS::Neutron::SecurityGroupRule
    properties:
      security_group: { get_resource: sg_linux_v6 }
      ethertype: IPv6
      protocol: icmpv6
      remote_ip_prefix: ::/0

# Servers
  puppet:
    type: OS::Nova::Server
    properties:
      name: puppet
      image: { get_param: os_image }
      flavor: { get_param: puppet_flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: core_net }
          fixed_ip: 192.168.0.10
      security_groups: [ 'default' , { get_resource: sg_linux_v4 }, { get_resource: sg_linux_v6 } ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: lib/puppetserver.sh }
          params:
            %%PUPPETSERVER%%: puppet
            %%DOMAIN%%: { get_param: domain }

  puppet_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_attr: [ puppet, addresses, get_param: core_net_name, 0, port ] }

