heat_template_version: 2018-08-31

description: >
  Deploy puppet infrastructure ready for use

parameters:
  core_net_name:
    type: string
    description: Name for core network
  core_net:
    type: string
    description: Core network ID
  domain:
    type: string
    description: Domain name for the deployed environment
  key_name:
    type: string
    description: SSH key for all servers
  os_image:
    type: string
    description: Default OS for all servers
    default: Ubuntu Server 20.04 LTS (Focal Fossa) amd64
  public_net:
    type: string
    description: ID or name of external net for router
  puppet_flavor:
    type: string
    description: Flavor for puppetmaster/puppetdb
  sec_groups:
    type: comma_delimited_list
    description: Default security groups
  environment:
    type: string
    description: Specify (puppet) envrionment. Typically production or test

resources:
  puppet:
    type: OS::Nova::Server
    properties:
      name: puppet
      image: { get_param: os_image }
      flavor: { get_param: puppet_flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_param: core_net }
          fixed_ip: 192.168.0.10
      security_groups: { get_param: sec_groups }
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: lib/puppetserver.bash }
          params:
            <%PUPPETSERVER%>: puppet
            <%DOMAIN%>: { get_param: domain }
            <%ENVIRONMENT%>: { get_param: environment }
            <%RABBITSERVER%>: rabbitmq
            <%PSQLSERVER%>: postgres

  puppet_fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_attr: [ puppet, addresses, get_param: core_net, 0, port ] }

